use crate::models::artifact::{Artifact, ArtifactEffect, Rarity};

pub fn all_artifacts() -> Vec<Artifact> {
    vec![
        // ── Common (5) ──
        Artifact {
            id: "iron_fan".into(),
            name_zh: "铁扇".into(),
            name_en: "Iron Fan".into(),
            description_zh: "每次出牌 +5 符".into(),
            rarity: Rarity::Common,
            cost: 50,
            sell_value: 25,
            effect: ArtifactEffect::AddFu(5),
        },
        Artifact {
            id: "jade_coin".into(),
            name_zh: "玉钱".into(),
            name_en: "Jade Coin".into(),
            description_zh: "每次出牌 +0.5 番".into(),
            rarity: Rarity::Common,
            cost: 60,
            sell_value: 30,
            effect: ArtifactEffect::AddFan(0.5),
        },
        Artifact {
            id: "bamboo_scroll".into(),
            name_zh: "竹简".into(),
            name_en: "Bamboo Scroll".into(),
            description_zh: "含刻子时 +2 番".into(),
            rarity: Rarity::Common,
            cost: 70,
            sell_value: 35,
            effect: ArtifactEffect::ConditionalAddFan { condition: "has_pon".into(), value: 2.0 },
        },
        Artifact {
            id: "wind_chime".into(),
            name_zh: "风铃".into(),
            name_en: "Wind Chime".into(),
            description_zh: "含风牌时 +1 番".into(),
            rarity: Rarity::Common,
            cost: 55,
            sell_value: 27,
            effect: ArtifactEffect::ConditionalAddFan { condition: "has_wind".into(), value: 1.0 },
        },
        Artifact {
            id: "dragon_scale".into(),
            name_zh: "龙鳞".into(),
            name_en: "Dragon Scale".into(),
            description_zh: "含三元牌时 +1 番".into(),
            rarity: Rarity::Common,
            cost: 55,
            sell_value: 27,
            effect: ArtifactEffect::ConditionalAddFan { condition: "has_dragon".into(), value: 1.0 },
        },

        // ── Uncommon (5) ──
        Artifact {
            id: "golden_turtle".into(),
            name_zh: "金龟".into(),
            name_en: "Golden Turtle".into(),
            description_zh: "每次出牌 +15 符".into(),
            rarity: Rarity::Uncommon,
            cost: 120,
            sell_value: 60,
            effect: ArtifactEffect::AddFu(15),
        },
        Artifact {
            id: "phoenix_feather".into(),
            name_zh: "凤羽".into(),
            name_en: "Phoenix Feather".into(),
            description_zh: "每次出牌 +1.5 番".into(),
            rarity: Rarity::Uncommon,
            cost: 150,
            sell_value: 75,
            effect: ArtifactEffect::AddFan(1.5),
        },
        Artifact {
            id: "growing_sprout".into(),
            name_zh: "成长的嫩芽".into(),
            name_en: "Growing Sprout".into(),
            description_zh: "每手出牌 +3 符（累计成长）".into(),
            rarity: Rarity::Uncommon,
            cost: 100,
            sell_value: 50,
            effect: ArtifactEffect::ScalingAddFu { per_round: 3, current: 0 },
        },
        Artifact {
            id: "tide_amulet".into(),
            name_zh: "潮汐护符".into(),
            name_en: "Tide Amulet".into(),
            description_zh: "含杠子时 ×2 倍率".into(),
            rarity: Rarity::Uncommon,
            cost: 130,
            sell_value: 65,
            effect: ArtifactEffect::ConditionalAddFan { condition: "has_kan".into(), value: 3.0 },
        },
        Artifact {
            id: "manzu_charm".into(),
            name_zh: "万子护符".into(),
            name_en: "Manzu Charm".into(),
            description_zh: "含万子时 +2 番".into(),
            rarity: Rarity::Uncommon,
            cost: 110,
            sell_value: 55,
            effect: ArtifactEffect::ConditionalAddFan { condition: "has_manzu".into(), value: 2.0 },
        },

        // ── Rare (5) ──
        Artifact {
            id: "heavenly_gong".into(),
            name_zh: "天锣".into(),
            name_en: "Heavenly Gong".into(),
            description_zh: "每次出牌 +30 符".into(),
            rarity: Rarity::Rare,
            cost: 250,
            sell_value: 125,
            effect: ArtifactEffect::AddFu(30),
        },
        Artifact {
            id: "demon_mirror".into(),
            name_zh: "妖镜".into(),
            name_en: "Demon Mirror".into(),
            description_zh: "每次出牌 ×1.5 倍率".into(),
            rarity: Rarity::Rare,
            cost: 300,
            sell_value: 150,
            effect: ArtifactEffect::MultiplyMult(1.5),
        },
        Artifact {
            id: "thunder_drum".into(),
            name_zh: "雷鼓".into(),
            name_en: "Thunder Drum".into(),
            description_zh: "每手出牌 +0.5 番（累计成长）".into(),
            rarity: Rarity::Rare,
            cost: 220,
            sell_value: 110,
            effect: ArtifactEffect::ScalingAddFan { per_round: 0.5, current: 0.0 },
        },
        Artifact {
            id: "crimson_lantern".into(),
            name_zh: "赤提灯".into(),
            name_en: "Crimson Lantern".into(),
            description_zh: "同花色时 +4 番".into(),
            rarity: Rarity::Rare,
            cost: 280,
            sell_value: 140,
            effect: ArtifactEffect::ConditionalAddFan { condition: "all_same_suit".into(), value: 4.0 },
        },
        Artifact {
            id: "twin_crane".into(),
            name_zh: "双鹤".into(),
            name_en: "Twin Crane".into(),
            description_zh: "含顺子时 +3 番".into(),
            rarity: Rarity::Rare,
            cost: 200,
            sell_value: 100,
            effect: ArtifactEffect::ConditionalAddFan { condition: "has_chi".into(), value: 3.0 },
        },

        // ── Legendary (5) ──
        Artifact {
            id: "imperial_seal".into(),
            name_zh: "玉玺".into(),
            name_en: "Imperial Seal".into(),
            description_zh: "每次出牌 ×2.0 倍率".into(),
            rarity: Rarity::Legendary,
            cost: 600,
            sell_value: 300,
            effect: ArtifactEffect::MultiplyMult(2.0),
        },
        Artifact {
            id: "nine_dragon_crown".into(),
            name_zh: "九龙冠".into(),
            name_en: "Nine Dragon Crown".into(),
            description_zh: "每次出牌 +50 符".into(),
            rarity: Rarity::Legendary,
            cost: 500,
            sell_value: 250,
            effect: ArtifactEffect::AddFu(50),
        },
        Artifact {
            id: "aotenjo_mirror".into(),
            name_zh: "青天井之镜".into(),
            name_en: "Aotenjo Mirror".into(),
            description_zh: "每次出牌 +5 番".into(),
            rarity: Rarity::Legendary,
            cost: 700,
            sell_value: 350,
            effect: ArtifactEffect::AddFan(5.0),
        },
        Artifact {
            id: "eternal_flame".into(),
            name_zh: "永恒之炎".into(),
            name_en: "Eternal Flame".into(),
            description_zh: "含端牌时 ×3.0 倍率".into(),
            rarity: Rarity::Legendary,
            cost: 550,
            sell_value: 275,
            effect: ArtifactEffect::ConditionalAddFan { condition: "has_terminal".into(), value: 8.0 },
        },
        Artifact {
            id: "samsara_wheel".into(),
            name_zh: "轮回之轮".into(),
            name_en: "Samsara Wheel".into(),
            description_zh: "每手出牌 +2 番（累计成长）".into(),
            rarity: Rarity::Legendary,
            cost: 650,
            sell_value: 325,
            effect: ArtifactEffect::ScalingAddFan { per_round: 2.0, current: 0.0 },
        },
    ]
}
